# Generated by Django 5.1.3 on 2024-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG_Chatbot', '0002_vectorstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_variable_name', models.TextField()),
                ('env_value', models.TextField()),
            ],
        ),
    ]
