# Generated by Django 5.1.3 on 2024-12-09 11:02

import RAG_Chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG_Chatbot', '0003_envvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotInteractionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(max_length=255, upload_to=RAG_Chatbot.models.upload_to_dynamic)),
                ('file_type', models.CharField(choices=[('Faiss_folder', 'FaissDB_Folder'), ('ChromaDB_folder', 'ChromaDB_Folder')], max_length=50)),
                ('db_type', models.CharField(max_length=50)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
